#@TYPE: Machine
#@NAME: orange-pi-4a
#@DESCRIPTION: Machine configuration for the orange-pi-4a, based on Allwinner T527 CPU

require conf/machine/include/sun55i.inc

KERNEL_DEVICETREE = "allwinner/sun55i-t527-orangepi-4a.dtb"
UBOOT_MACHINE = "orangepi_4a_defconfig"
IMAGE_BOOT_FILES = "${KERNEL_IMAGETYPE} boot.scr ${@d.getVar('KERNEL_DEVICETREE', '').split('/')[-1]};${KERNEL_DEVICETREE}}"

MACHINE_EXTRA_RRECOMMENDS = "kernel-modules"